[build]
  base = "home"
  command = "npm run build"
  publish = "build"

[build.environment]
  REACT_APP_API_BASE_URL = "https://srbuj3d-production.up.railway.app/api"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
